### ISSUE TITLE
Instalation guide

### ISSUE THREAD

**Issue by aryopg** [CreDevLabz/Merchant#1]
I'm totally new in magento world, especially in making or installing modules like this. Can i get a thorough explanation on how to install this module whether using composer or other ways? Thank you in advance

**Comment by amansrivastava** [comment]
@aryopg Thanks for showing interest in the module but it is still in dev and repo is not updated from a long time as It is just a small piece of big picture.
Working on this on spare time so this is not bound with any timeline yet.
